[project]
name = "oclabs"
version = "0.1.0"
description = "Opt Pulse" Recommendation Engine 3.0 by OC Labs
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.127.0",
    "openai-agents>=0.6.4",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.40.0",
]
